name: Test
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install black flake8 pytest
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Python Linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true

      - name: Test with pytest
        run: |
          pytest test_*.py --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: junit/*
          retention-days: 5
